name: Haberman Survival Prediction
on: [push]
jobs:
  runPipeline:
    runs-on: [ubuntu-latest]
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest]
    #runs-on: ${{matrix.os}}
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout_and_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md master > report.md
          dvc params diff --show-md master >> report.md
          cml-send-comment report.md
